---
- name: Upgrade all packages
  become: true
  block:
    - name: Install deltarpm
      ansible.builtin.yum:
        name:
          - deltarpm
        state: present
      when:
        - ansible_distribution < '8'
    - name: Update all packages
      ansible.builtin.yum:
        state: latest
        update_cache: yes
        update_only: yes
