---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu2204
    image: ubuntu:22.04
  - name: ubuntu2404
    image: ubuntu:24.04
  - name: centos-stream9
    image: quay.io/centos/centos:stream9
provisioner:
  name: ansible
scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
